name: ImageRAG
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.9.24=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.15=h5eee18b_0
  - pip=24.2=py310h06a4308_0
  - python=3.10.13=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.44.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - accelerate==1.1.1
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.10
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anyio==4.7.0
      - async-timeout==4.0.3
      - attrs==24.2.0
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - git+https://github.com/openai/CLIP.git
      - contourpy==1.3.1
      - cycler==0.12.1
      - datasets==3.1.0
      - diffusers==0.31.0
      - dill==0.3.8
      - distro==1.9.0
      - exceptiongroup==1.2.2
      - filelock==3.13.1
      - fonttools==4.55.2
      - frozenlist==1.5.0
      - fsspec==2024.2.0
      - ftfy==6.3.1
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.26.2
      - idna==3.10
      - importlib-metadata==8.5.0
      - jinja2==3.1.3
      - jiter==0.8.0
      - kiwisolver==1.4.7
      - markupsafe==2.1.5
      - matplotlib==3.9.3
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - networkx==3.2.1
      - numpy==1.26.3
      - open-clip-torch==2.29.0
      - openai==1.57.0
      - opencv-python==4.12.0.88
      - packaging==24.2
      - pandas==2.2.3
      - peft==0.13.2
      - pillow==10.2.0
      - propcache==0.2.0
      - psutil==6.1.0
      - pyarrow==18.0.0
      - pydantic==2.10.3
      - pydantic-core==2.27.1
      - pyparsing==3.2.0
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - pyyaml==6.0.2
      - rank-bm25==0.2.2
      - regex==2024.11.6
      - requests==2.32.3
      - safetensors==0.4.5
      - six==1.16.0
      - sniffio==1.3.1
      - sympy==1.13.1
      - timm==1.0.11
      - tokenizers==0.20.3
      - torch==2.4.1
      - torchvision==0.19.1
      - tqdm==4.67.0
      - transformers==4.46.2
      - triton==3.0.0
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - urllib3==2.2.3
      - wcwidth==0.2.13
      - xxhash==3.5.0
      - yarl==1.17.1
      - zipp==3.21.0
